Feat/nl dev 52
new-lantern/nl-ohif pull request #20
Opened 2021-11-23 19:52 UTC by legend620

### PR Checklist

- [ ] Brief description of changes
- [ ] Links to any relevant issues
- [ ] Required status checks are passing
- [ ] User cases if changes impact the user's experience
- [ ] `@mention` a maintainer to request a review

[blog]: https://circleci.com/blog/triggering-trusted-ci-jobs-on-untrusted-forks/
[script]: https://github.com/jklukas/git-push-fork-to-upstream-branch

2021-11-23 22:10 UTC, ryan00012 approved these changes

2021-11-23 22:11 UTC, ryan00012 commented on platform/core/src/services/ViewerToolsetService/ViewerToolset.js
> -  setIsCrosshairsEnabled: _setIsCrosshairsEnabled,
Why is setIsCrosshairsEnabled removed now? Should it have both Crosshairs and seriesLinking?

2021-11-23 22:13 UTC, ryan00012 commented on platform/core/src/services/ViewerToolsetService/ViewerToolset.js
> +  _setIsSeriesLinkingEnabled: () =>
Same here:  Why is setIsCrosshairsEnabled removed now and replaced with series linking. Applies to rest of th e PR too

2021-11-24 05:53 UTC, shivasuri commented on extensions/cornerstone/src/commandsModule.js
> +      // });
Can we delete these lines?

2021-11-24 06:53 UTC, shivasuri requested changes
Just tested out locally, and wow it looks great 💯🙌🏻
Just one thing: Series Linking should work for series of same orientation across different studies. Other than that, everything is awesome.

2021-11-24 11:42 UTC, legend620 commented on extensions/cornerstone/src/commandsModule.js
> +      // });
yes

2021-11-25 23:19 UTC, shivasuri commented on extensions/cornerstone/src/initSeriesLinking.js
> +        // }
delete?

2021-11-25 23:24 UTC, shivasuri approved these changes

2021-11-25 23:25 UTC, legend620 commented on extensions/cornerstone/src/initSeriesLinking.js
> +        // }
yes we can delete

2021-11-26 02:02 UTC, merged